name: yabo_bank
description: sistem informasi sampah

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_form_builder: ^3.5.4
  shared_preferences : ^0.5.4
  http: any
  # image_picker: 0.4.12+1
  image_picker: 0.6.3+1
  path_provider: 
  permission_handler:
  image: any
  mime: ^0.9.6+3
  toast: ^0.1.5
  pull_to_refresh: ^1.4.5
  date_range_picker: ^1.0.5
  url_launcher: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/logo.png"
  image_path_android: "assets/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/flutterwithlogo.png
    - assets/logo.png
    - assets/alucard.jpg
    - assets/images/powered_by.png
    - assets/images/email_icon.png
    - assets/images/password_icon.png
    - assets/images/user_icon.png
    - assets/images/as.png
    - assets/images/placehoder.jpg
  fonts:
      - family: Nunito
        fonts:
          - asset: assets/Nunito.ttf
      - family: Ubuntu
        fonts:
          - asset: packages/ubuntu_font_flutter/Ubuntu-R.ttf
          - asset: packages/ubuntu_font_flutter/Ubuntu-RI.ttf
            style: italic
          - asset: packages/ubuntu_font_flutter/Ubuntu-B.ttf
            weight: 700
          - asset: packages/ubuntu_font_flutter/Ubuntu-BI.ttf
            weight: 700
            style: italic
          - asset: packages/ubuntu_font_flutter/Ubuntu-L.ttf
            weight: 300
          - asset: packages/ubuntu_font_flutter/Ubuntu-LI.ttf
            weight: 300
            style: italic
          - asset: packages/ubuntu_font_flutter/Ubuntu-M.ttf
            weight: 500
          - asset: packages/ubuntu_font_flutter/Ubuntu-MI.ttf
            weight: 500
            style: italic
      - family: Ubuntu Mono
        fonts:
          - asset: packages/ubuntu_font_flutter/UbuntuMono-R.ttf
          - asset: packages/ubuntu_font_flutter/UbuntuMono-RI.ttf
            style: italic
          - asset: packages/ubuntu_font_flutter/UbuntuMono-B.ttf
            weight: 700
          - asset: packages/ubuntu_font_flutter/UbuntuMono-BI.ttf
            weight: 700
            style: italic
      - family: Ubuntu Condensed
        fonts:
          - asset: packages/ubuntu_font_flutter/Ubuntu-C.ttf

